# docker-compose.yaml SIMPLES para Orchestrator no EasyPanel
# SEM VPN - Para uso normal do orchestrator
services:
  orchestrator_app:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8000:8000"
    volumes:
      - orchestrator_data:/app/data
      - orchestrator_logs:/app/logs
    environment:
      # --- PostgreSQL INTERNO (Orchestrator) ---
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-orchestrator}
      - DB_USER=${DB_USER:-orchestrator_user}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # --- PostgreSQL EXTERNO (Streams) ---
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_TABLE_NAME=${DB_TABLE_NAME:-streams}
      
      # --- Servidor ---
      - ORCHESTRATOR_HOST=${ORCHESTRATOR_HOST:-0.0.0.0}
      - ORCHESTRATOR_PORT=${ORCHESTRATOR_PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-America/Sao_Paulo}
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  orchestrator_data:
  orchestrator_logs: