services:
      gluetun:
        image: qmcgaw/gluetun:latest
        cap_add:
          - NET_ADMIN
        devices:
          - /dev/net/tun:/dev/net/tun
        volumes:
          - gluetun_data:/gluetun
        environment:
          # --- Configuração da VPN (Plano Pago - Dinâmico via Variáveis) ---
          # Estas serão lidas das Variáveis de Ambiente do EasyPanel
          - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-protonvpn}
          - VPN_TYPE=${VPN_TYPE:-wireguard}
          # --- Seleção de Servidor (Definida nas Variáveis do EasyPanel) ---
          # Exemplo: - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Brazil}
          # Remova as linhas fixas daqui se definir na UI, ou deixe um padrão
          - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Brazil}
          # --- Chave Privada e Credenciais (Definidas nas Variáveis do EasyPanel) ---
          # As variáveis WIREGUARD_PEER_* NÃO devem ser definidas para seleção dinâmica
          - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
          - OPENVPN_USER=${VPN_USER}
          - OPENVPN_PASSWORD=${VPN_PASSWORD}
          # --- Outras Opções ---
          - TZ=${TZ:-America/Sao_Paulo}
        # --- Healthcheck com Parâmetros Relaxados ---
        healthcheck:
          test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
          interval: 20s
          timeout: 10s
          retries: 5
          start_period: 30s
        restart: unless-stopped

      finger_app:
        # --- USA A IMAGEM PRÉ-CONSTRUÍDA DO DOCKER HUB ---
        # !!! SUBSTITUA pela sua imagem e tag reais !!!
        image: jrprod/finger_app:paidvpn-v3
        network_mode: "service:gluetun"
        depends_on:
          gluetun:
            condition: service_healthy
        volumes:
          - app_segments:/app/segments
          # Opcional: Montar código local
          # - /opt/finger_vpn_package/app:/app
        environment:
          # --- Variáveis da Aplicação (Definidas no EasyPanel) ---
          - POSTGRES_HOST=${POSTGRES_HOST}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_PORT=${POSTGRES_PORT:-5432}
          - DB_TABLE_NAME=${DB_TABLE_NAME:-music_log}
          - SERVER_ID=${SERVER_ID:-1}
          - TOTAL_SERVERS=${TOTAL_SERVERS:-1}
          - DISTRIBUTE_LOAD=${DISTRIBUTE_LOAD:-False}
          # ENABLE_ROTATION e ROTATION_HOURS removidos - agora usa sistema de hashing consistente
          - IDENTIFICATION_DURATION=${IDENTIFICATION_DURATION:-15}
          - DUPLICATE_PREVENTION_WINDOW_SECONDS=${DUPLICATE_PREVENTION_WINDOW_SECONDS:-900}
          - SEGMENTS_DIR=/app/segments
          - PYTHONUNBUFFERED=1
          - TZ=${TZ:-America/Sao_Paulo}
          # Adicione outras variáveis que seu fingerv7.py precise ler
        restart: unless-stopped

    volumes:
      gluetun_data:
      app_segments:
